### ISSUE TITLE
Extrapolation function broke down today

### ISSUE THREAD

**Issue by ErwinM** [JeroenKools/covid19#2]
Hi,

We are using your script to run daily numbers at our company - just to inform ourselves. 

Since today, the logistics function suddenly returns an overflow error. I am well versed in Python, but not so much in curve fitting. Any chance you can point me in the right direction?

Thanks for your work.

**Comment by ErwinM** [comment]
Johns Hopkins changed the naming of some countries some days ago. Those changes I've made in the covid19.py script found in my fork of your repo: https://github.com/ErwinM/covid19

**Comment by JeroenKools** [comment]
Hi Erwin,

The overflow warning is for an intermediate estimate that doesn't get used; parameters that would result in an overflow are out of bounds. But the warning message is kind of confusing, so I changed it to not display the warning (365317308ffa9377b4c083c8a094c8b64b6b5ab6).

As for the country names, can you be more specific? I am aware that some names changed, but to my knowledge the current version of the notebook is not having any issues with that.
