### ISSUE TITLE
germany dropped out of the smoothed growth factor graph

### ISSUE THREAD

**Issue by stockh0lm** [JeroenKools/covid19#3]
that figure (and the comparison to the rest of the world) was the unique feature that i came to see. That graph did grow a little hard to read, too. can perhaps the javacode for presenting it be tweaked to not show all graphs and store that information in a cookie??? this is outside my juniper skill range. but i hope you find a way to bring germany back into the smoothed growth factor graph

**Comment by JeroenKools** [comment]
You're in luck, it's back by popular request!

Also, if you want to look at another set of countries, it's easy to do so in [Colab](https://colab.research.google.com/github/JeroenKools/covid19/blob/master/COVID-19.ipynb).

Modify the list of countries, then select **Runtime > Run all** from the menu and it should generate  fresh result for the countries of your choice.

**Comment by stockh0lm** [comment]
_"Want to see these graphs for some other countries, or modify the values for the simulations? The easiest and quickest way to run the notebook and make modifications yourself is to open this notebook in Colab."_

is that new? i certainly missed it before. thank you!
