### ISSUE TITLE
Growth factor

### ISSUE THREAD

**Issue by hpschlenvoigt** [JeroenKools/covid19#4]
Hi Jeroen,
due to the change of dataformat and especially the drop of recovered cases by JHU data repo, I stumbled to your project. I have a similar one, where I a calculate from the time series data the active cases (as potentially contagious) and the daily change. Among others, I plot something silimilar to the "official" growth factor R: daily new cases per active cases, what is basically R-1. However, then it makes much sense to use also a logy scale. That is what I want to suggest to you. Then you can see easier how the numbers develop over time, how effective lockdowns are and how long they need to be effective etc. In addition, I am using hvplot.pandas what give you mousewheel-zoomable interactive plots.
Cheers

**Comment by JeroenKools** [comment]
Hi @hpschlenvoigt, check out the "new confirmed/active" plot in my latest commit; is that what you had in mind?

Thanks for suggesting hvplot, it looks very useful!
