### ISSUE TITLE
About parameters

### ISSUE THREAD

**Issue by ypriverol** [JeroenKools/covid19#5]
Dear @JeroenKools:

First, thanks for this notebook, really useful. Im trying to use it with Cuban data. I came across these three parameters:

```python
M = 0.25              # mitigation effectiveness under major lockdown
W = 0.50              # mitigation effectiveness under weak lockdown
N = 1.00              # mitigation effectiveness under normal conditions
```  

How did you estimate these three parameters? Are they based on real data? Can they be estimated from the existing data in the country? 

Thanks

**Comment by JeroenKools** [comment]
Hi @ypriverol,

Those values are mere guesstimates, except for 1.00 for normal conditions, which implies that the R0 is unchanged). I suppose we could look at the Chinese or South Korean data to see how effective their mitigation efforts were.

**Comment by ypriverol** [comment]
@JeroenKools:

I'm not a mathematician but will be good to have a value something like: 

```python
K=?   Assuming Korea Model
Ch=?  Assuming China Model
```
How we can estimate this?

**Comment by JeroenKools** [comment]
@ypriverol: See the [latest commit](9d7f3bb7fd09b8ca67fad87e5e5698f624a75d8b). Thanks for the suggestion!

**Comment by ypriverol** [comment]
Thanks a lot. Playing with the new functionality.
